language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "aureamohammadalavi"
    token:
secure: "ZhQKIpBuw0yy5i+9CqfUQH2RAZaF0Gdh56CGdQSt/pGG5hzGo7ctQnxLZIjLm2RsFEyX2Nz4TFMTpFGj8i162phSuLU71uQJFmmgrrwsAbVtq+cHn0gGirty6LfSG96X4J9XxITxSHyfr0uAxuOmnLcuF+cc/lutM/UH/ewnwRSr9XyRhcLuMAkjtxAx2rko6eHgt4wnXTDdCUcHGWVQ9P3B+DpmHXtldhl93JzyojjfQoKRUnPRvBmq3tEgfttDXR/bF9FtG9ySb+EGaK1rdXvTZmcMMHfJT1AHMepfz95kB9fK+ZI22flv4Y3w7NZljP2FNlp7AthefhDxQeALZQiJwBnrTADsv9/uAE7APlUiLuOX/Ukfb4bamHxceijNzeRrcMPae0LTDFuMKbY1uf57b5s2p2oRai5/xoHR/RtxA06Q5n3rYMWAjblwY2m4LBK8LI4wwAjNnrqUcG8DfhbEp3oi043EQhaH8qtfNhvpngJE4Y7yF/GGhBgDsEZXQ6N2wekaoIlrIhE3z6o0BqJ4YXEPIktbSw4Vsscsewftbswo8xhefFXdBnJ9GNvaNrxChXDtyLrphbJ5BA0MoSbKfMuIC0P9Ny0/3xV10YMwq4ghqD+M6+MbBcbcuC5FEMLcwDUepP5ffLAqoLKJrCpGlxaNGFbKsTDFIHaiXQc="

jdk:
  - oraclejdk11

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  -  mvn sonar:sonar   -Dsonar.projectKey=AureaMohammadAlavi_SonarDemo   -Dsonar.organization=aureamohammadalavi   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=a56cfbb38a3eab90c5660278fa1b347344f55de2


